// this file version.go was generated by build.go

package safelist

func GetVersion() *Version {
	return &Version{
		Version:    "v0.0.1-dev",
		CommitHash: "21b91d2fbc45779c4df7e2b25dab1b942794a2c3",
		Date:       "2023-11-27T16:57:17Z",
	}
}

type Version struct {
	Version    string `json:"version"`
	CommitHash string `json:"commitHash"`
	Date       string `json:"date"`
}
